apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-nginx
  template:
    metadata:
      labels:
        app: proxy-nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx/nginx:latest
          ports:
            - containerPort: 80
