---
apiVersion: v1
kind: Service
metadata:
  name: webmailer-proxy-service
spec:
  type: LoadBalancer
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8080
      targetPort: 80
      nodePort: 30080
  selector:
    app: webmailer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webmailer-proxy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webmailer
  template:
    metadata:
      labels:
        app: webmailer
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
            - containerPort: 80
