apiVersion: apps/v1
kind: Deployment
metadata:
  name: roundcube-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-fpm-roundcube
  template:
    metadata:
      labels:
        app: php-fpm-roundcube
    spec:
      containers:
        - name: roundcube-container
          image: roundcube/roundcubemail:latest-fpm
          ports:
            - containerPort: 9000
